version: '3.8'

services:
  remotion-api:
    build: .
    container_name: remotion-api
    volumes:
      - ./output:/app/output
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=3000
    # Configurações de recursos para melhor performance
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4G
        reservations:
          cpus: '2.0'
          memory: 2G
    # Configurações de segurança
    security_opt:
      - seccomp:unconfined
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - npm-internal

networks:
  npm-internal:
    external: true
